### ISSUE TITLE
Syscall wrappers should sanity-check return values from untrusted ocalls

### ISSUE THREAD

**Issue by david-oswald** [keystone-enclave/keystone-runtime#21] opened 2019-08-19 20:27 UTC
Currently, the in-enclave syscall wrappers just pass through the return value from the untrusted ocall, e.g., here:

https://github.com/keystone-enclave/keystone-runtime/blob/master/io_wrap.c#L130

it is not checked that `ret <= len`. This might cause a problem if an eapp uses a pattern like this:

```
while (bytes_in_buff > 0)
{
    size_t block_size = (bytes_in_buff < 128) ? bytes_in_buff : 128;
    size_t bytes_sent = write(1, buff, block_size); // to stdout
    
    if (bytes_sent < 0)
    {
        // fail
        break;
    }
    
    buff += bytes_sent;
    bytes_in_buff -= bytes_sent;
    i++;
    printf("\n %d byte written, %d remaining\n", bytes_sent, bytes_in_buff);
}
```

In this case, if the untrusted runtime returns e.g. a larger value for the final block, the above code will continue outputting enclave memory beyond bounds.

Overall, this attack scenario is quite similar to Iago attacks (https://hovav.net/ucsd/dist/iago.pdf).

Here a small patch, that, when applied to the keystone-sdk, demonstrates this issue (run the `hello` example) :
[write-syscall-return.zip](https://github.com/keystone-enclave/keystone-runtime/files/3517528/write-syscall-return.zip)

I know that you are aware that using libc from an eapp does not really guarantee a secure interface, but I think it would still make sense to prevent such relatively generic attacks.

The above obviously is not restricted to `write()`, but to all syscalls returning a value that might be interpreted as length/offset/pointer inside the eapp.

**Comment by dayeol** [comment] 2019-08-21 00:43
Thank you for reporting this and providing the POC!
We are aware that current implementation will not prevent Iago attacks,
but the issue is very helpful for us to motivate the improvements.
I also think that the generic attacks should be prevented by default.

**Comment by david-oswald** [comment] 2019-08-29 06:22
I agree that it would probably better from a security point-of-view to implement something similar to Intel's EDL first (writing all the edge code manually is obviously error-prone), rather than having a full-fledged libc with all the potential problems.

**Comment by dkohlbre** [comment] 2019-09-03 17:33
OK.
I'll close this for now, we're looking into porting over something like: https://arxiv.org/pdf/1807.00477.pdf as an Eyrie plugin.
We'll label the current interface appropriately.

**Closed by dkohlbre** 2019-09-03 17:33 UTC
Labels: good first issue
